#!/usr/bin/env bash

set -eu

curl -fsSL -o ../get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
chmod 700 ../get_helm.sh
../get_helm.sh
echo "Using Helm version: $(helm version --short)"

repo_uri="https://x-access-token:${DEPLOY_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
remote_name="origin"
main_branch="main"
target_branch="gh-pages"
build_dir="dist"
cd "$GITHUB_WORKSPACE"

echo "Checking Helm chart dependencies..."
helm dependency update
echo "Building Helm chart..."
helm package --destination ../ .
echo "Cleanup..."
if [[ -e Chart.lock ]]; then rm Chart.lock; fi
if [[ -d charts ]]; then mv charts tmp_charts; fi

git config user.name "$GITHUB_ACTOR"
git config user.email "${GITHUB_ACTOR}@bots.github.com"

git checkout "$target_branch"
#git rebase "${remote_name}/${main_branch}"

mv ../*.tgz .
echo "Updating dependencies..."
for file in $(find tmp_charts -name "*.tgz"); do
    if [[ ! -e charts/$(basename $file) ]]; then 
        echo "  $(basename $file)"
        mv "$file" charts/ 
    fi
done
rm -rf tmp_charts

helm repo index .

git add -A

git commit -m "updated GitHub Pages"
if [ $? -ne 0 ]; then
    echo "nothing to commit"
    exit 0
fi

git remote set-url "$remote_name" "$repo_uri"
git push --force-with-lease "$remote_name" "$target_branch"