{{- if .Values.initialJob.enabled }}
{{- range $url := .Values.targetUrl }}
{{- $jobName := regexReplaceAll "https://([^./]+).*" $url "$1" | trunc 63 | trimSuffix "-" -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "zaproxy.fullname" $ }}-{{ $jobName }}
  labels:
    app.kubernetes.io/component: {{ include "zaproxy.fullname" $ }}
    release: {{ $.Release.Name }}
spec:
  backoffLimit: 0
  {{- if $.Values.initialJob.cleanupAfterDays }}
  ttlSecondsAfterFinished: {{ mul $.Values.initialJob.cleanupAfterDays 86400 }}
  {{- end }}
  template:
    spec:
      containers:
        - name: zaproxy
          image: {{ $.Values.image.repository }}:{{ default $.Chart.AppVersion $.Values.image.tag }}
          imagePullPolicy: {{ $.Values.image.pullPolicy | quote }}
          resources:
            requests:
              cpu: {{ $.Values.resources.requests.cpu }}
              memory: {{ $.Values.resources.requests.memory }}
            limits:
              cpu: {{ $.Values.resources.limits.cpu }}
              memory: {{ $.Values.resources.limits.memory }}
          command:
            - /bin/sh
            - -c
            - |
              DATE=$(date +%Y%m%d)
              zap-full-scan.py \
                -t {{ $url }} \
                -c /zap/config/zap.cfg \
                -r /zap/wrk/{{ $jobName }}-$DATE.html \
                -J /zap/wrk/{{ $jobName }}-$DATE.json || true
          volumeMounts:
            - mountPath: /zap/config
              name: config
            - mountPath: /zap/wrk
              name: data
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            name: {{ include "zaproxy.fullname" $ }}-config
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "zaproxy.fullname" $ }}-data
---
{{- end }}
{{- end }}