name: GitHub Pages

on:
    release:
      types: # This configuration does not affect the page_build event above
        - created
        - prereleased 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        - run: .bin/update-gh-pages
          env:
            DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }} 
            GITHUB_TOKEN: ${{ secrets.github_token }}